spring:
  config:
    activate:
      on-profile: default
#
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: "thecommercethecommercethecommercethecommercethecommercethecommercethecommerce"
  token:
    expired-time: 86400000

  swagger-ui:
    path: /swagger-ui
    enabled: true



